appName:
  app: nginx-prod
replicas: 5
nodeSelector:
  kubernetes.io/hostname: node5-prod
  testing: prod-testing
container:
  name: nginx-prod-cont
  image: nginx:1.22.1
  pullPolicy: Always
  port: 80
  envs:
    - name: POSTGRES_USERNAME
      value: postgres-sql-prod
    - name: POSTGRES_PASSWORD
      value: s348432sdfbsfewff
    - name: POSTGRES_DB
      value: db_prod