#!/bin/bash

create-instance:
    echo "Createing frist Google instance wtih ssh pub key"
    # ansible-playbook playbooks/create-gcp-instanceV2.yaml --vault-password-file vars/vault-data--credentail-pass.txt
    ansible-playbook playbooks/create-gcp-instanceV2.yaml --vault-password-file vars/password.txt

create-master:
    echo "Creating master instance ..."
    ansible-playbook playbooks/create-masters-instace.yaml

create-worker:
    echo "Creating worker instance ..."
    ansible-playbook playbooks/create-workers-instance.yaml

iac: 
    echo "Create all the masters ....  " 
    ansible-playbook playbooks/create-masters-instace.yaml
    echo "Create all the workers ..... " 
    ansible-playbook playbooks/create-workers-instance.yaml
